// 50 Top-Selling US SUVs Data
const TOP_50_SUVS = [
  // 1. Toyota RAV4 Hybrid (Sweet Spot)
  {
    id: 'toyota-rav4-hybrid',
    name: 'Toyota RAV4 Hybrid',
    brand: 'Toyota',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Compact',
    msrp: 31725,
    mpgCombined: 39,
    cityMpg: 41,
    highwayMpg: 38,
    seatingCapacity: 5,
    cargoVolumeCuFt: 37.5,
    acceleration0to60Sec: 7.3,
    drivetrain: 'AWD',
    overallScore: 9.6,
    imageUrl: './images/Toyota-RAV4-Hybrid.webp',
    tagline:
      'America’s #1 selling hybrid SUV with legendary reliability and standard AWD.',
    pros: [
      'Exceptional resale value',
      'Standard electronic AWD',
      'Spacious cargo bay',
      'Infotainment with wireless CarPlay',
    ],
    cons: ['Engine noise under heavy acceleration', 'Firm rear suspension'],
    keyFeatures: [
      'Standard Toyota Safety Sense 3.0',
      '39 MPG Combined',
      'Available Woodland Edition',
    ],
    usSalesRank: 1,
    isSweetSpot: true,
  },

  // 2. Kia Niro Hybrid (Best Budget)
  {
    id: 'kia-niro-hybrid',
    name: 'Kia Niro Hybrid',
    brand: 'Kia',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Subcompact',
    msrp: 26990,
    mpgCombined: 49,
    cityMpg: 53,
    highwayMpg: 45,
    seatingCapacity: 5,
    cargoVolumeCuFt: 22.8,
    acceleration0to60Sec: 8.9,
    drivetrain: 'FWD',
    overallScore: 9.4,
    imageUrl: './images/Kia-Niro-Hybrid.webp',
    tagline:
      'The ultimate fuel economy champion under $27k with stunning 49 MPG efficiency.',
    pros: [
      'Incredible 49 MPG combined',
      'Unbeatable starting price',
      '10-year/100,000-mile warranty',
      'High-tech cabin',
    ],
    cons: ['No AWD option', 'Slower acceleration'],
    keyFeatures: [
      'Dual 10.25-inch panoramic screens',
      'Best-in-class mpg',
      'Smart Regenerative Braking',
    ],
    usSalesRank: 12,
    isBestBudget: true,
  },

  // 3. Tesla Model Y (Full EV)
  {
    id: 'tesla-model-y',
    name: 'Tesla Model Y',
    brand: 'Tesla',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Compact',
    msrp: 44990,
    mpgCombined: 122, // MPGe
    cityMpg: 127,
    highwayMpg: 117,
    electricRangeMiles: 310,
    batteryKwh: 75,
    seatingCapacity: 5,
    cargoVolumeCuFt: 76.2,
    acceleration0to60Sec: 4.8,
    drivetrain: 'AWD',
    overallScore: 9.5,
    imageUrl: './images/Tesla-Model-Y.webp',
    tagline:
      'The highest-selling electric crossover in history with unmatched Supercharger access.',
    pros: [
      'Zero gasoline required',
      'Access to Tesla Supercharger Network',
      'Blistering acceleration',
      'Massive cargo space with frunk',
    ],
    cons: ['Minimal physical controls', 'Ride can be stiff on rough roads'],
    keyFeatures: [
      'Autopilot included',
      '15-inch touchscreen center console',
      '310 miles EPA range',
    ],
    usSalesRank: 2,
    isBestEV: true,
  },

  // 4. Honda CR-V Hybrid
  {
    id: 'honda-crv-hybrid',
    name: 'Honda CR-V Hybrid',
    brand: 'Honda',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Compact',
    msrp: 34350,
    mpgCombined: 40,
    cityMpg: 43,
    highwayMpg: 36,
    seatingCapacity: 5,
    cargoVolumeCuFt: 39.3,
    acceleration0to60Sec: 7.9,
    drivetrain: 'AWD / FWD',
    overallScore: 9.5,
    imageUrl: './images/Honda-CR-V-Hybrid.webp',
    tagline:
      'Smooth, refined hybrid driving with ultra-spacious rear seats and cargo area.',
    pros: [
      'Ultra-refined drive feel',
      'Massive back seat legroom',
      'Intuitive controls',
      'High resale value',
    ],
    cons: ['Slightly higher starting price than RAV4', 'No spare tire'],
    keyFeatures: [
      '204-hp hybrid system',
      'Honda Sensing standard',
      '39.3 cu ft trunk space',
    ],
    usSalesRank: 3,
  },

  // 5. Hyundai Tucson Hybrid
  {
    id: 'hyundai-tucson-hybrid',
    name: 'Hyundai Tucson Hybrid',
    brand: 'Hyundai',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Compact',
    msrp: 32575,
    mpgCombined: 38,
    cityMpg: 38,
    highwayMpg: 38,
    seatingCapacity: 5,
    cargoVolumeCuFt: 38.7,
    acceleration0to60Sec: 7.1,
    drivetrain: 'AWD',
    overallScore: 9.3,
    imageUrl: './images/Hyundai-Tucson-Hybrid.webp',
    tagline:
      'Futuristic design packed with luxury tech, standard AWD, and 226 horsepower.',
    pros: [
      'Punchy 226-hp turbocharged powertrain',
      '10-yr powertrain warranty',
      'Standard AWD',
      'Quiet cabin',
    ],
    cons: [
      'Distinctive styling is love-it or hate-it',
      'Touch controls can fingerprint',
    ],
    keyFeatures: [
      'Standard HTRAC AWD',
      '12.3-inch curved digital display',
      'Remote Smart Parking Assist',
    ],
    usSalesRank: 5,
  },

  // 6. Ford Escape PHEV
  {
    id: 'ford-escape-phev',
    name: 'Ford Escape Plug-In Hybrid',
    brand: 'Ford',
    modelYear: 2026,
    powertrain: 'Plug-in Hybrid',
    category: 'Compact',
    msrp: 40500,
    mpgCombined: 101, // MPGe
    cityMpg: 42,
    highwayMpg: 36,
    electricRangeMiles: 37,
    batteryKwh: 14.4,
    seatingCapacity: 5,
    cargoVolumeCuFt: 34.4,
    acceleration0to60Sec: 7.7,
    drivetrain: 'FWD',
    overallScore: 8.9,
    imageUrl: './images/Ford-Escape-Plug-In-Hybrid.webp',
    tagline:
      '37 miles of electric commuting plus hybrid gas efficiency for road trips.',
    pros: [
      '37 miles electric range handles daily commute',
      'SYNC 4 wireless Apple CarPlay',
      'Sliding 2nd-row seats',
    ],
    cons: ['Front-wheel drive only', 'Some hard cabin plastics'],
    keyFeatures: [
      '101 MPGe combined',
      '13.2-inch center screen',
      'Eligible for state tax rebates',
    ],
    usSalesRank: 15,
  },

  // 7. Hyundai Ioniq 5
  {
    id: 'hyundai-ioniq-5',
    name: 'Hyundai Ioniq 5',
    brand: 'Hyundai',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Compact',
    msrp: 41800,
    mpgCombined: 114,
    cityMpg: 132,
    highwayMpg: 98,
    electricRangeMiles: 303,
    batteryKwh: 77.4,
    seatingCapacity: 5,
    cargoVolumeCuFt: 59.3,
    acceleration0to60Sec: 5.0,
    drivetrain: 'AWD / RWD',
    overallScore: 9.6,
    imageUrl: './images/Hyundai-Ioniq-5.webp',
    tagline:
      'Ultra-fast 800V charging (10-80% in 18 mins) with retro-futuristic pixel styling.',
    pros: [
      'Industry-leading charging speed',
      'Lounge-like spacious interior',
      'Ultra-smooth whisper drive',
    ],
    cons: ['No rear wiper on older trims', 'Smaller rear trunk than Model Y'],
    keyFeatures: [
      '800V Ultra-Fast Charging',
      'Vehicle-to-Load (V2L) power outlet',
      '303-mile maximum range',
    ],
    usSalesRank: 8,
  },

  // 8. Kia Sportage Hybrid
  {
    id: 'kia-sportage-hybrid',
    name: 'Kia Sportage Hybrid',
    brand: 'Kia',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Compact',
    msrp: 28590,
    mpgCombined: 43,
    cityMpg: 42,
    highwayMpg: 44,
    seatingCapacity: 5,
    cargoVolumeCuFt: 39.5,
    acceleration0to60Sec: 7.2,
    drivetrain: 'FWD / AWD',
    overallScore: 9.4,
    imageUrl: './images/Kia-Sportage-Hybrid.webp',
    tagline:
      'Class-leading rear legroom and trunk space with impressive 43 MPG rating.',
    pros: [
      'Sub-$29k starting MSRP',
      '43 MPG rating on FWD models',
      'Dual panoramic curved displays',
    ],
    cons: ['Bold front grille not for everyone'],
    keyFeatures: [
      'Best rear legroom in class',
      '227-hp hybrid powertrain',
      '10-year warranty',
    ],
    usSalesRank: 6,
  },

  // 9. Lexus RX 350h
  {
    id: 'lexus-rx-350h',
    name: 'Lexus RX 350h Hybrid',
    brand: 'Lexus',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Luxury',
    msrp: 52100,
    mpgCombined: 36,
    cityMpg: 37,
    highwayMpg: 34,
    seatingCapacity: 5,
    cargoVolumeCuFt: 29.6,
    acceleration0to60Sec: 7.4,
    drivetrain: 'AWD',
    overallScore: 9.3,
    imageUrl: './images/Lexus-RX-350h-Hybrid.webp',
    tagline:
      'The quintessential luxury hybrid SUV with cloud-like comfort and rock-solid reliability.',
    pros: [
      'Ultra-quiet cabin',
      'Supple ride quality',
      'Top-tier reliability scores',
      '36 MPG in a luxury midsize',
    ],
    cons: [
      'Infotainment interface takes learning',
      'Touch buttons on steering wheel',
    ],
    keyFeatures: [
      'Mark Levinson 21-speaker audio available',
      'Standard Lexus Safety System+ 3.0',
      'Electronic AWD',
    ],
    usSalesRank: 10,
  },

  // 10. Toyota Highlander Hybrid
  {
    id: 'toyota-highlander-hybrid',
    name: 'Toyota Highlander Hybrid',
    brand: 'Toyota',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: '3-Row',
    msrp: 41220,
    mpgCombined: 36,
    cityMpg: 36,
    highwayMpg: 35,
    seatingCapacity: 8,
    cargoVolumeCuFt: 84.3,
    acceleration0to60Sec: 7.8,
    drivetrain: 'AWD / FWD',
    overallScore: 9.2,
    imageUrl: './images/Toyota-Highlander-Hybrid.webp',
    tagline:
      'The gold standard family 3-row SUV delivering 36 MPG across all rows.',
    pros: [
      'Seats up to 8 passengers',
      '36 MPG combined in a 3-row SUV',
      'High resale value',
      'Reliable hybrid battery',
    ],
    cons: ['Tight 3rd row for adults'],
    keyFeatures: [
      'Toyota Safety Sense 2.5+',
      '3,500 lbs towing capacity',
      '36 MPG combined',
    ],
    usSalesRank: 7,
  },

  // 11. Chevrolet Equinox EV
  {
    id: 'chevrolet-equinox-ev',
    name: 'Chevrolet Equinox EV',
    brand: 'Chevrolet',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Compact',
    msrp: 34995,
    mpgCombined: 108,
    cityMpg: 117,
    highwayMpg: 99,
    electricRangeMiles: 319,
    batteryKwh: 85,
    seatingCapacity: 5,
    cargoVolumeCuFt: 57.2,
    acceleration0to60Sec: 5.9,
    drivetrain: 'FWD / AWD',
    overallScore: 9.1,
    imageUrl: './images/Chevrolet-Equinox-EV.webp',
    tagline:
      '319 miles of range under $35k MSRP makes this an EV price breakthrough.',
    pros: [
      'Unbeatable range-per-dollar ratio',
      'Super Cruise hands-free driving option',
      'Large 17.7-inch display',
    ],
    cons: ['No native Apple CarPlay / Android Auto (uses Google Built-in)'],
    keyFeatures: [
      '319-mile EPA range FWD',
      'Super Cruise hands-free driving',
      '17.7-inch infotainment touchscreen',
    ],
    usSalesRank: 14,
  },

  // 12. Subaru Crosstrek Hybrid
  {
    id: 'subaru-crosstrek-hybrid',
    name: 'Subaru Crosstrek Hybrid',
    brand: 'Subaru',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Subcompact',
    msrp: 31000,
    mpgCombined: 38,
    cityMpg: 38,
    highwayMpg: 37,
    seatingCapacity: 5,
    cargoVolumeCuFt: 20.8,
    acceleration0to60Sec: 8.2,
    drivetrain: 'AWD',
    overallScore: 9.0,
    imageUrl: './images/Subaru-Crosstrek-Hybrid.webp',
    tagline:
      'Symmetrical All-Wheel Drive meets 8.7 inches ground clearance for eco adventures.',
    pros: [
      'Rugged off-road capability',
      'Standard Symmetrical AWD',
      '8.7-inch ground clearance',
    ],
    cons: ['Modest cargo bay'],
    keyFeatures: [
      'Subaru EyeSight Driver Assist',
      'X-MODE off-road system',
      '38 MPG combined',
    ],
    usSalesRank: 11,
  },

  // 13. Mazda CX-50 Hybrid
  {
    id: 'mazda-cx50-hybrid',
    name: 'Mazda CX-50 Hybrid',
    brand: 'Mazda',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Compact',
    msrp: 33970,
    mpgCombined: 38,
    cityMpg: 39,
    highwayMpg: 37,
    seatingCapacity: 5,
    cargoVolumeCuFt: 31.4,
    acceleration0to60Sec: 7.5,
    drivetrain: 'AWD',
    overallScore: 9.3,
    imageUrl: './images/Mazda-CX-50-Hybrid.webp',
    tagline:
      'Toyota hybrid reliability married to Mazda handling and upscale cabin materials.',
    pros: [
      'Toyota 38 MPG hybrid powertrain',
      'Near-luxury interior trim',
      'Sporty handling dynamics',
    ],
    cons: ['Firm ride quality'],
    keyFeatures: [
      'Standard AWD',
      'Terracotta leather interior options',
      'Power panoramic moonroof',
    ],
    usSalesRank: 18,
  },

  // 14. Kia EV6
  {
    id: 'kia-ev6',
    name: 'Kia EV6',
    brand: 'Kia',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Compact',
    msrp: 42600,
    mpgCombined: 117,
    cityMpg: 136,
    highwayMpg: 100,
    electricRangeMiles: 310,
    batteryKwh: 77.4,
    seatingCapacity: 5,
    cargoVolumeCuFt: 50.2,
    acceleration0to60Sec: 4.6,
    drivetrain: 'RWD / AWD',
    overallScore: 9.4,
    imageUrl: './images/Kia-EV6.webp',
    tagline:
      'Sleek sports crossover styling with lightning fast DC charging and GT performance options.',
    pros: [
      'Ultra-fast charging',
      'Distinctive sporty design',
      'Agile cornering',
    ],
    cons: ['Slanted roofline reduces rear cargo height'],
    keyFeatures: [
      '800V architecture',
      'Vehicle-to-Load utility',
      '310 miles EPA range',
    ],
    usSalesRank: 19,
  },

  // 15. Lexus NX 350h
  {
    id: 'lexus-nx-350h',
    name: 'Lexus NX 350h Hybrid',
    brand: 'Lexus',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Luxury',
    msrp: 44615,
    mpgCombined: 39,
    cityMpg: 41,
    highwayMpg: 37,
    seatingCapacity: 5,
    cargoVolumeCuFt: 22.7,
    acceleration0to60Sec: 7.2,
    drivetrain: 'AWD',
    overallScore: 9.2,
    imageUrl: './images/Lexus-NX-350h-Hybrid.webp',
    tagline: '39 MPG combined in a compact luxury crossover under $45k MSRP.',
    pros: [
      '39 MPG efficiency in luxury segment',
      'Lexus Interface with 14-inch display',
      'Plush seating',
    ],
    cons: ['Small trunk volume'],
    keyFeatures: [
      'Standard AWD',
      'Lexus Safety System+ 3.0',
      '14-inch touchscreen',
    ],
    usSalesRank: 20,
  },

  // 16. Volvo XC60 Recharge
  {
    id: 'volvo-xc60-recharge',
    name: 'Volvo XC60 Recharge PHEV',
    brand: 'Volvo',
    modelYear: 2026,
    powertrain: 'Plug-in Hybrid',
    category: 'Luxury',
    msrp: 58050,
    mpgCombined: 63, // MPGe
    cityMpg: 28,
    highwayMpg: 28,
    electricRangeMiles: 35,
    batteryKwh: 18.8,
    seatingCapacity: 5,
    cargoVolumeCuFt: 22.4,
    acceleration0to60Sec: 4.5,
    drivetrain: 'AWD',
    overallScore: 9.2,
    imageUrl: './images/Volvo-XC60-Recharge-PHEV.webp',
    tagline:
      '455 horsepower PHEV rocket delivering 35 miles EV range and Scandinavian luxury.',
    pros: [
      'Stunning 455 horsepower output',
      '35 miles all-electric driving',
      'World-class safety scores',
      'Bowers & Wilkins sound system option',
    ],
    cons: ['High price point'],
    keyFeatures: [
      '455 hp AWD powertrain',
      'Google Built-In infotainment',
      '35-mile electric range',
    ],
    usSalesRank: 25,
  },

  // 17. Ford Explorer Hybrid
  {
    id: 'ford-explorer-hybrid',
    name: 'Ford Explorer Hybrid',
    brand: 'Ford',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: '3-Row',
    msrp: 47000,
    mpgCombined: 27,
    cityMpg: 27,
    highwayMpg: 28,
    seatingCapacity: 7,
    cargoVolumeCuFt: 87.8,
    acceleration0to60Sec: 6.8,
    drivetrain: 'RWD / AWD',
    overallScore: 8.6,
    imageUrl: './images/Ford-Explorer-Hybrid.webp',
    tagline:
      'Rugged 3-row family SUV capable of towing up to 5,000 lbs with hybrid economy.',
    pros: [
      '5,000 lbs towing capacity',
      'Powerful 318-hp V6 hybrid setup',
      'Spacious 3rd row',
    ],
    cons: ['Lower mpg than compact hybrids'],
    keyFeatures: [
      'Ford Co-Pilot360',
      '5,000 lbs towing capacity',
      'Class IV Trailer Tow Package',
    ],
    usSalesRank: 9,
  },

  // 18. Toyota Grand Highlander Hybrid
  {
    id: 'toyota-grand-highlander-hybrid',
    name: 'Toyota Grand Highlander Hybrid',
    brand: 'Toyota',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: '3-Row',
    msrp: 45020,
    mpgCombined: 36,
    cityMpg: 37,
    highwayMpg: 34,
    seatingCapacity: 8,
    cargoVolumeCuFt: 97.5,
    acceleration0to60Sec: 7.5,
    drivetrain: 'AWD',
    overallScore: 9.6,
    imageUrl: './images/Toyota-Grand-Highlander-Hybrid.webp',
    tagline:
      'Adult-friendly 3rd row seating + massive cargo area + 36 MPG combined economy.',
    pros: [
      'Huge 3rd row legroom for adults',
      '36 MPG in a giant family SUV',
      'Hybrid MAX 362-hp option available',
    ],
    cons: ['Long waiting lists'],
    keyFeatures: [
      '97.5 cu ft max cargo space',
      '12.3-inch touchscreen standard',
      '36 MPG efficiency',
    ],
    usSalesRank: 4,
  },

  // 19. Honda Prologue EV
  {
    id: 'honda-prologue-ev',
    name: 'Honda Prologue EV',
    brand: 'Honda',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Midsize',
    msrp: 47400,
    mpgCombined: 107,
    cityMpg: 116,
    highwayMpg: 99,
    electricRangeMiles: 296,
    batteryKwh: 85,
    seatingCapacity: 5,
    cargoVolumeCuFt: 57.7,
    acceleration0to60Sec: 5.8,
    drivetrain: 'AWD / FWD',
    overallScore: 9.1,
    imageUrl: './images/Honda-Prologue-EV.webp',
    tagline:
      'Honda’s first all-electric midsize crossover with 296 miles range and spacious cabin.',
    pros: [
      'Smooth ride quality',
      'Generous rear seat space',
      'Google Built-in navigation with EV route planning',
    ],
    cons: ['Moderate fast-charging speeds'],
    keyFeatures: [
      '296-mile EPA range',
      'Wireless Apple CarPlay & Android Auto',
      'Panoramic sunroof',
    ],
    usSalesRank: 22,
  },

  // 20. Toyota Crown Signia
  {
    id: 'toyota-crown-signia',
    name: 'Toyota Crown Signia Hybrid',
    brand: 'Toyota',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Midsize',
    msrp: 43590,
    mpgCombined: 38,
    cityMpg: 39,
    highwayMpg: 37,
    seatingCapacity: 5,
    cargoVolumeCuFt: 68.8,
    acceleration0to60Sec: 7.1,
    drivetrain: 'AWD',
    overallScore: 9.3,
    imageUrl: './images/Toyota-Crown-Signia-Hybrid.webp',
    tagline:
      'Near-Lexus luxury wagon/SUV hybrid replacement for the Venza with 38 MPG.',
    pros: [
      'Ultra-quiet cabin',
      'Supple leather seats',
      'Standard AWD and 243-hp output',
      'Fold-flat 6.5ft cargo bed',
    ],
    cons: ['No 3rd row option'],
    keyFeatures: [
      '243-hp hybrid powertrain',
      'Standard AWD',
      '6.5-foot flat cargo load floor',
    ],
    usSalesRank: 23,
  },

  // 21. Rivian R1S
  {
    id: 'rivian-r1s',
    name: 'Rivian R1S',
    brand: 'Rivian',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Luxury',
    msrp: 75900,
    mpgCombined: 82,
    cityMpg: 85,
    highwayMpg: 78,
    electricRangeMiles: 410,
    batteryKwh: 135,
    seatingCapacity: 7,
    cargoVolumeCuFt: 105.0,
    acceleration0to60Sec: 3.0,
    drivetrain: 'AWD',
    overallScore: 9.5,
    imageUrl: './images/Rivian-R1S.webp',
    tagline:
      'The ultimate electric 7-passenger adventure SUV with up to 410 miles range and 3.0s 0-60.',
    pros: [
      'Up to 410-mile range options',
      'Phenomenal off-road capability',
      'Unmatched storage options (frunk + underfloor)',
      'Seats 7 comfortably',
    ],
    cons: ['Premium price tag', 'No Apple CarPlay'],
    keyFeatures: [
      'Air suspension with 14.9-in clearance',
      'Dual, Tri, or Quad-Motor AWD',
      '410 miles max range',
    ],
    usSalesRank: 26,
  },

  // 22. BMW X5 xDrive50e
  {
    id: 'bmw-x5-xdrive50e',
    name: 'BMW X5 xDrive50e PHEV',
    brand: 'BMW',
    modelYear: 2026,
    powertrain: 'Plug-in Hybrid',
    category: 'Luxury',
    msrp: 73100,
    mpgCombined: 58, // MPGe
    cityMpg: 22,
    highwayMpg: 23,
    electricRangeMiles: 39,
    batteryKwh: 25.7,
    seatingCapacity: 5,
    cargoVolumeCuFt: 33.1,
    acceleration0to60Sec: 4.6,
    drivetrain: 'AWD',
    overallScore: 9.4,
    imageUrl: './images/BMW-X5-xDrive50e-PHEV.webp',
    tagline:
      '483 horsepower luxury plug-in hybrid delivering 39 electric miles and supreme BMW dynamics.',
    pros: [
      '483 hp inline-6 turbo PHEV engine',
      '39 miles pure EV range',
      'iDrive 8.5 curved display',
      'Superb driving dynamics',
    ],
    cons: ['Expensive options list'],
    keyFeatures: [
      '483 hp combined power',
      'Adaptive air suspension',
      '39-mile electric range',
    ],
    usSalesRank: 27,
  },

  // 23. Nissan Rogue
  {
    id: 'nissan-rogue',
    name: 'Nissan Rogue VC-Turbo',
    brand: 'Nissan',
    modelYear: 2026,
    powertrain: 'Gas',
    category: 'Compact',
    msrp: 29230,
    mpgCombined: 33,
    cityMpg: 30,
    highwayMpg: 37,
    seatingCapacity: 5,
    cargoVolumeCuFt: 36.5,
    acceleration0to60Sec: 7.8,
    drivetrain: 'FWD / AWD',
    overallScore: 8.8,
    imageUrl: './images/Nissan-Rogue-VC-Turbo.webp',
    tagline:
      'America’s top gas-only compact SUV delivering 33 MPG with Zero Gravity seats.',
    pros: [
      '33 MPG gas efficiency',
      'Ultra-comfortable Zero Gravity seats',
      'Divide-N-Hide cargo floor',
    ],
    cons: ['3-cylinder variable compression engine feel'],
    keyFeatures: [
      'ProPILOT Assist 1.1',
      'Google Built-In infotainment',
      '33 MPG combined',
    ],
    usSalesRank: 13,
  },

  // 24. Jeep Wrangler 4xe
  {
    id: 'jeep-wrangler-4xe',
    name: 'Jeep Wrangler 4xe PHEV',
    brand: 'Jeep',
    modelYear: 2026,
    powertrain: 'Plug-in Hybrid',
    category: 'Midsize',
    msrp: 50695,
    mpgCombined: 49, // MPGe
    cityMpg: 20,
    highwayMpg: 20,
    electricRangeMiles: 21,
    batteryKwh: 17.3,
    seatingCapacity: 5,
    cargoVolumeCuFt: 27.7,
    acceleration0to60Sec: 6.0,
    drivetrain: 'AWD',
    overallScore: 8.7,
    imageUrl: './images/Jeep-Wrangler-4xe-PHEV.webp',
    tagline:
      'America’s #1 best-selling plug-in hybrid — legendary trail capability with 21 miles EV mode.',
    pros: [
      'Unmatched off-road king status',
      '#1 selling PHEV in USA',
      '375 hp / 470 lb-ft torque',
    ],
    cons: ['Wind noise on highway', '20 MPG once battery exhausts'],
    keyFeatures: [
      'Removable doors and top',
      '375 hp 4xe powertrain',
      '21 miles EV range',
    ],
    usSalesRank: 16,
  },

  // 25. Kia Telluride
  {
    id: 'kia-telluride',
    name: 'Kia Telluride V6',
    brand: 'Kia',
    modelYear: 2026,
    powertrain: 'Gas',
    category: '3-Row',
    msrp: 36190,
    mpgCombined: 22,
    cityMpg: 20,
    highwayMpg: 26,
    seatingCapacity: 8,
    cargoVolumeCuFt: 87.0,
    acceleration0to60Sec: 6.8,
    drivetrain: 'FWD / AWD',
    overallScore: 9.6,
    imageUrl: './images/Kia-Telluride-V6.webp',
    tagline:
      'Multiple-time SUV of the Year award winner with benchmark 3-row luxury design.',
    pros: [
      'Stunning range-topping interior',
      'Generous 3rd row and cargo',
      '10-year powertrain warranty',
      'Great value proposition',
    ],
    cons: ['22 MPG gas economy'],
    keyFeatures: [
      'Dual 12.3-inch displays',
      '5,500 lbs max towing',
      'Highway Driving Assist 2',
    ],
    usSalesRank: 17,
  },

  // 26. Hyundai Palisade
  {
    id: 'hyundai-palisade',
    name: 'Hyundai Palisade V6',
    brand: 'Hyundai',
    modelYear: 2026,
    powertrain: 'Gas',
    category: '3-Row',
    msrp: 36650,
    mpgCombined: 22,
    cityMpg: 19,
    highwayMpg: 26,
    seatingCapacity: 8,
    cargoVolumeCuFt: 86.4,
    acceleration0to60Sec: 6.9,
    drivetrain: 'FWD / AWD',
    overallScore: 9.5,
    imageUrl: './images/Hyundai-Palisade-V6.webp',
    tagline:
      'First-class 3-row family cruiser with heated 3rd-row seats and Ergo Motion driver seat.',
    pros: [
      'Near-Genesis interior materials',
      'Heated seats in all 3 rows available',
      'Remote Smart Parking Assist',
    ],
    cons: ['V6 fuel economy is average'],
    keyFeatures: [
      'Ergo Motion massaging driver seat',
      '12.3-inch screen standard',
      '5,000 lbs towing',
    ],
    usSalesRank: 21,
  },

  // 27. Subaru Forester Hybrid
  {
    id: 'subaru-forester-hybrid',
    name: 'Subaru Forester Hybrid',
    brand: 'Subaru',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Compact',
    msrp: 34500,
    mpgCombined: 38,
    cityMpg: 39,
    highwayMpg: 36,
    seatingCapacity: 5,
    cargoVolumeCuFt: 29.6,
    acceleration0to60Sec: 8.0,
    drivetrain: 'AWD',
    overallScore: 9.2,
    imageUrl: './images/Subaru-Forester-Hybrid.webp',
    tagline:
      'Subaru’s famous boxy visibility and symmetrical AWD upgraded with Toyota hybrid power.',
    pros: [
      'Unmatched outward visibility',
      '8.7-inch ground clearance',
      'Symmetrical AWD standard',
      '38 MPG combined',
    ],
    cons: ['Subtle design evolution'],
    keyFeatures: [
      'Subaru EyeSight Driver Assist',
      'Subaru Starlink 11.6-inch screen',
      '38 MPG combined',
    ],
    usSalesRank: 24,
  },

  // 28. Mazda CX-90 PHEV
  {
    id: 'mazda-cx90-phev',
    name: 'Mazda CX-90 PHEV',
    brand: 'Mazda',
    modelYear: 2026,
    powertrain: 'Plug-in Hybrid',
    category: '3-Row',
    msrp: 49945,
    mpgCombined: 56, // MPGe
    cityMpg: 25,
    highwayMpg: 25,
    electricRangeMiles: 26,
    batteryKwh: 17.8,
    seatingCapacity: 8,
    cargoVolumeCuFt: 75.2,
    acceleration0to60Sec: 5.9,
    drivetrain: 'AWD',
    overallScore: 9.3,
    imageUrl: './images/Mazda-CX-90-PHEV.webp',
    tagline:
      '323-horsepower premium 3-row crossover with 26 electric miles and rear-biased AWD.',
    pros: [
      'Luxury Japanese craftsmanship',
      '323 hp dynamic powertrain',
      '26 miles EV range for errands',
    ],
    cons: ['Snug 3rd row cargo space'],
    keyFeatures: [
      'Kinematic Posture Control',
      '323 hp e-Skyactiv PHEV',
      '3,500 lbs towing',
    ],
    usSalesRank: 28,
  },

  // 29. Volkswagen ID.4 EV
  {
    id: 'volkswagen-id4',
    name: 'Volkswagen ID.4 EV',
    brand: 'Volkswagen',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Compact',
    msrp: 39735,
    mpgCombined: 107,
    cityMpg: 115,
    highwayMpg: 98,
    electricRangeMiles: 291,
    batteryKwh: 82,
    seatingCapacity: 5,
    cargoVolumeCuFt: 64.2,
    acceleration0to60Sec: 5.0,
    drivetrain: 'RWD / AWD',
    overallScore: 8.9,
    imageUrl: './images/Volkswagen-ID4-EV.webp',
    tagline:
      'Quiet German engineering in an accessible electric family crossover built in Tennessee.',
    pros: [
      'Very comfortable, supple ride',
      'Spacious rear seating',
      'Eligible for US federal tax credit',
    ],
    cons: ['Infotainment interface touch sliders'],
    keyFeatures: [
      'Up to 291-mile EPA range',
      '12.9-inch updated display',
      'IQ.DRIVE safety suite',
    ],
    usSalesRank: 29,
  },

  // 30. Ford Mustang Mach-E
  {
    id: 'ford-mustang-mach-e',
    name: 'Ford Mustang Mach-E',
    brand: 'Ford',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Compact',
    msrp: 39995,
    mpgCombined: 103,
    cityMpg: 110,
    highwayMpg: 96,
    electricRangeMiles: 320,
    batteryKwh: 91,
    seatingCapacity: 5,
    cargoVolumeCuFt: 59.7,
    acceleration0to60Sec: 3.5,
    drivetrain: 'RWD / AWD',
    overallScore: 9.3,
    imageUrl: './images/Ford-Mustang-Mach-E.webp',
    tagline:
      'Thrilling Mustang soul in an electric SUV with BlueCruise hands-free driving.',
    pros: [
      'BlueCruise hands-free highway driving',
      'Exhilarating GT 3.5s acceleration',
      'Drainable front trunk (frunk)',
    ],
    cons: ['Firm sport suspension on rough pavement'],
    keyFeatures: [
      'Up to 320 miles range',
      '15.5-inch vertical Sync 4A screen',
      'BlueCruise 1.3',
    ],
    usSalesRank: 30,
  },

  // 31. Kia EV9
  {
    id: 'kia-ev9',
    name: 'Kia EV9 EV',
    brand: 'Kia',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: '3-Row',
    msrp: 54900,
    mpgCombined: 89,
    cityMpg: 98,
    highwayMpg: 78,
    electricRangeMiles: 304,
    batteryKwh: 99.8,
    seatingCapacity: 7,
    cargoVolumeCuFt: 81.7,
    acceleration0to60Sec: 4.5,
    drivetrain: 'RWD / AWD',
    overallScore: 9.6,
    imageUrl: './images/Kia-EV9-EV.webp',
    tagline:
      'World Car of the Year winner — the first affordable full-size 3-row EV with 800V fast charging.',
    pros: [
      'Adult-sized 3rd row in an EV',
      '10-80% charge in 24 minutes',
      'Swiveling 2nd-row seats available',
      'Bold boxy stance',
    ],
    cons: ['Large footprint for tight urban parking'],
    keyFeatures: [
      '304-mile maximum range',
      '5,000 lbs towing capacity',
      '800V ultra-fast charging',
    ],
    usSalesRank: 31,
  },

  // 32. Lexus TX 500h
  {
    id: 'lexus-tx-500h',
    name: 'Lexus TX 500h F SPORT Performance',
    brand: 'Lexus',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: '3-Row',
    msrp: 69350,
    mpgCombined: 27,
    cityMpg: 27,
    highwayMpg: 28,
    seatingCapacity: 7,
    cargoVolumeCuFt: 97.0,
    acceleration0to60Sec: 6.1,
    drivetrain: 'AWD',
    overallScore: 9.3,
    imageUrl: './images/Lexus-TX-500h-F-SPORT-Performance.webp',
    tagline:
      '366-hp luxury 3-row crossover tailored specifically for American family road trips.',
    pros: [
      '366 hp turbocharged hybrid setup',
      'DIRECT4 AWD torque vectoring',
      'Massive cargo capacity behind 3rd row',
    ],
    cons: ['27 MPG combined is lower than compacts'],
    keyFeatures: [
      'DIRECT4 AWD system',
      '366 hp combined output',
      '14-inch Lexus Interface',
    ],
    usSalesRank: 32,
  },

  // 33. Cadillac LYRIQ
  {
    id: 'cadillac-lyriq',
    name: 'Cadillac LYRIQ EV',
    brand: 'Cadillac',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Luxury',
    msrp: 57195,
    mpgCombined: 95,
    cityMpg: 101,
    highwayMpg: 89,
    electricRangeMiles: 314,
    batteryKwh: 102,
    seatingCapacity: 5,
    cargoVolumeCuFt: 60.8,
    acceleration0to60Sec: 4.6,
    drivetrain: 'RWD / AWD',
    overallScore: 9.2,
    imageUrl: './images/Cadillac-LYRIQ-EV.webp',
    tagline:
      '33-inch curved 9K LED screen with Super Cruise hands-free driving in a ultra-quiet luxury package.',
    pros: [
      'Breathtaking 33-inch curved 9K display',
      'Standard Super Cruise capability',
      '500 hp AWD option',
    ],
    cons: ['Heavy curb weight'],
    keyFeatures: [
      '33-inch 9K LED display',
      'Super Cruise hands-free driver assistance',
      '314 miles range',
    ],
    usSalesRank: 33,
  },

  // 34. Toyota Corolla Cross Hybrid
  {
    id: 'toyota-corolla-cross-hybrid',
    name: 'Toyota Corolla Cross Hybrid',
    brand: 'Toyota',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Subcompact',
    msrp: 28220,
    mpgCombined: 42,
    cityMpg: 45,
    highwayMpg: 38,
    seatingCapacity: 5,
    cargoVolumeCuFt: 21.5,
    acceleration0to60Sec: 7.3,
    drivetrain: 'AWD',
    overallScore: 9.1,
    imageUrl: './images/Toyota-Corolla-Cross-Hybrid.webp',
    tagline:
      'Subcompact footprint + standard AWD + 42 MPG combined for under $29k MSRP.',
    pros: [
      'Standard Electronic AWD',
      '42 MPG combined efficiency',
      '196 horsepower (faster than gas version)',
    ],
    cons: ['Rear seat is compact'],
    keyFeatures: [
      '196-hp Fifth-Gen Hybrid System',
      'Standard AWD',
      'Toyota Safety Sense 3.0',
    ],
    usSalesRank: 34,
  },

  // 35. Hyundai Kona Electric
  {
    id: 'hyundai-kona-electric',
    name: 'Hyundai Kona Electric',
    brand: 'Hyundai',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Subcompact',
    msrp: 32875,
    mpgCombined: 116,
    cityMpg: 129,
    highwayMpg: 103,
    electricRangeMiles: 261,
    batteryKwh: 64.8,
    seatingCapacity: 5,
    cargoVolumeCuFt: 25.5,
    acceleration0to60Sec: 7.5,
    drivetrain: 'FWD',
    overallScore: 9.0,
    imageUrl: './images/Hyundai-Kona-Electric.webp',
    tagline:
      'High-value subcompact EV crossover loaded with futuristic pixel lighting and twin 12.3-in displays.',
    pros: [
      'Dual 12.3-inch panoramic screens',
      'Vehicle-to-Load (V2L) capability',
      'Great city maneuverability',
    ],
    cons: ['FWD only'],
    keyFeatures: [
      '261 miles range',
      'Twin 12.3-inch screens',
      'Over-The-Air software updates',
    ],
    usSalesRank: 35,
  },

  // 36. Jeep Grand Cherokee 4xe
  {
    id: 'jeep-grand-cherokee-4xe',
    name: 'Jeep Grand Cherokee 4xe PHEV',
    brand: 'Jeep',
    modelYear: 2026,
    powertrain: 'Plug-in Hybrid',
    category: 'Midsize',
    msrp: 60490,
    mpgCombined: 56, // MPGe
    cityMpg: 23,
    highwayMpg: 24,
    electricRangeMiles: 26,
    batteryKwh: 17.3,
    seatingCapacity: 5,
    cargoVolumeCuFt: 37.7,
    acceleration0to60Sec: 5.3,
    drivetrain: 'AWD',
    overallScore: 8.9,
    imageUrl: './images/Jeep-Grand-Cherokee-4xe-PHEV.webp',
    tagline:
      'Premium midsize SUV luxury with 375 hp, Quadra-Lift air suspension, and 26-mile EV mode.',
    pros: [
      '375 hp / 470 lb-ft torque',
      '6,000 lbs towing capacity',
      'Passenger interactive screen option',
    ],
    cons: ['Upper trims get expensive'],
    keyFeatures: [
      '375 hp PHEV powertrain',
      '6,000 lbs towing capacity',
      'McIntosh 19-speaker audio available',
    ],
    usSalesRank: 36,
  },

  // 37. Nissan Ariya EV
  {
    id: 'nissan-ariya',
    name: 'Nissan Ariya EV',
    brand: 'Nissan',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Compact',
    msrp: 39590,
    mpgCombined: 101,
    cityMpg: 109,
    highwayMpg: 94,
    electricRangeMiles: 304,
    batteryKwh: 87,
    seatingCapacity: 5,
    cargoVolumeCuFt: 59.7,
    acceleration0to60Sec: 4.8,
    drivetrain: 'FWD / AWD',
    overallScore: 9.0,
    imageUrl: './images/Nissan-Ariya-EV.webp',
    tagline:
      'Lounge-style Japanese minimalist cabin with e-4ORCE twin-motor AWD precision control.',
    pros: [
      'Lounge-like open front cabin',
      'Power sliding center console',
      'Smooth e-4ORCE AWD control',
    ],
    cons: ['Slower charging curve than 800V rivals'],
    keyFeatures: [
      'ProPILOT Assist 2.0 hands-free',
      '304-mile max range',
      'e-4ORCE All-Wheel Drive',
    ],
    usSalesRank: 37,
  },

  // 38. Toyota Land Cruiser Hybrid
  {
    id: 'toyota-land-cruiser-hybrid',
    name: 'Toyota Land Cruiser i-FORCE MAX',
    brand: 'Toyota',
    modelYear: 2026,
    powertrain: 'Hybrid',
    category: 'Midsize',
    msrp: 55950,
    mpgCombined: 23,
    cityMpg: 22,
    highwayMpg: 25,
    seatingCapacity: 5,
    cargoVolumeCuFt: 37.5,
    acceleration0to60Sec: 7.7,
    drivetrain: 'AWD',
    overallScore: 9.4,
    imageUrl: './images/Toyota-Land-Cruiser-i-FORCE-MAX.webp',
    tagline:
      'The iconic off-road legend returns with standard 326-hp hybrid power and retro styling.',
    pros: [
      '326 hp / 465 lb-ft torque',
      'Standard Full-Time 4WD with locking differentials',
      'Heritage retro design',
    ],
    cons: ['23 MPG is modest for hybrid class'],
    keyFeatures: [
      'i-FORCE MAX 2.4L Turbo Hybrid',
      '6,000 lbs towing capacity',
      'Disconnecting front sway bar',
    ],
    usSalesRank: 38,
  },

  // 39. BMW iX
  {
    id: 'bmw-ix',
    name: 'BMW iX xDrive50 EV',
    brand: 'BMW',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Luxury',
    msrp: 87250,
    mpgCombined: 83,
    cityMpg: 86,
    highwayMpg: 85,
    electricRangeMiles: 307,
    batteryKwh: 111.5,
    seatingCapacity: 5,
    cargoVolumeCuFt: 77.9,
    acceleration0to60Sec: 4.4,
    drivetrain: 'AWD',
    overallScore: 9.5,
    imageUrl: './images/BMW-iX-xDrive50-EV.webp',
    tagline:
      '516 horsepower electric flagship with self-healing kidney grille and crystal controls.',
    pros: [
      '516 hp dual-motor power',
      'Ultra-luxurious futuristic cabin',
      'Bowers & Wilkins 3D Diamond Surround Sound option',
    ],
    cons: ['Polarizing exterior styling'],
    keyFeatures: [
      '516 hp dual-motor AWD',
      'Curved Display with iDrive 8.5',
      '307-mile range',
    ],
    usSalesRank: 39,
  },

  // 40. Subaru Outback
  {
    id: 'subaru-outback',
    name: 'Subaru Outback AWD',
    brand: 'Subaru',
    modelYear: 2026,
    powertrain: 'Gas',
    category: 'Midsize',
    msrp: 28895,
    mpgCombined: 28,
    cityMpg: 26,
    highwayMpg: 32,
    seatingCapacity: 5,
    cargoVolumeCuFt: 32.6,
    acceleration0to60Sec: 8.6,
    drivetrain: 'AWD',
    overallScore: 9.3,
    imageUrl: './images/Subaru-Outback-AWD.webp',
    tagline:
      'The ultimate utility wagon/SUV hybrid with standard Symmetrical AWD and roof rails.',
    pros: [
      'Wagon accessibility with 8.7-inch ground clearance',
      'Superior safety scores',
      'Integrated retractable roof crossbars',
    ],
    cons: ['Base engine acceleration is relaxed'],
    keyFeatures: [
      'Standard Symmetrical AWD',
      '11.6-inch STARLINK touchscreen',
      'EyeSight Driver Assist',
    ],
    usSalesRank: 15,
  },

  // 41. Mitsubishi Outlander PHEV
  {
    id: 'mitsubishi-outlander-phev',
    name: 'Mitsubishi Outlander PHEV',
    brand: 'Mitsubishi',
    modelYear: 2026,
    powertrain: 'Plug-in Hybrid',
    category: 'Compact',
    msrp: 40345,
    mpgCombined: 64, // MPGe
    cityMpg: 26,
    highwayMpg: 26,
    electricRangeMiles: 38,
    batteryKwh: 20,
    seatingCapacity: 7,
    cargoVolumeCuFt: 64.7,
    acceleration0to60Sec: 7.6,
    drivetrain: 'AWD',
    overallScore: 8.8,
    imageUrl: './images/Mitsubishi-Outlander-PHEV.webp',
    tagline:
      'Rare 3-row compact SUV offering 38 miles electric range and S-AWC rally-derived AWD.',
    pros: [
      '38 miles EV range',
      '3-row seating in a compact crossover',
      'Super All-Wheel Control (S-AWC)',
      '10-yr warranty',
    ],
    cons: ['3rd row is tight for adults'],
    keyFeatures: [
      'Super All-Wheel Control (S-AWC)',
      '38 miles EV range',
      '10-year/100k warranty',
    ],
    usSalesRank: 40,
  },

  // 42. Genesis GV70 Electrified
  {
    id: 'genesis-gv70-electrified',
    name: 'Genesis Electrified GV70 EV',
    brand: 'Genesis',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Luxury',
    msrp: 66950,
    mpgCombined: 91,
    cityMpg: 98,
    highwayMpg: 83,
    electricRangeMiles: 236,
    batteryKwh: 77.4,
    seatingCapacity: 5,
    cargoVolumeCuFt: 56.5,
    acceleration0to60Sec: 3.8,
    drivetrain: 'AWD',
    overallScore: 9.4,
    imageUrl: './images/Genesis-Electrified-GV70-EV.webp',
    tagline:
      '483-hp Boost Mode thrill in a stunning Korean luxury crossover with 800V fast charging.',
    pros: [
      '483 hp Boost Mode button on steering wheel',
      'Bespoke Nappa leather cabin',
      '18-minute fast charge',
    ],
    cons: ['236 miles range is modest'],
    keyFeatures: [
      '483 hp Boost Mode',
      '800V charging',
      'Genesis Concierge service included',
    ],
    usSalesRank: 41,
  },

  // 43. Audi Q5 55 TFSI e PHEV
  {
    id: 'audi-q5-phev',
    name: 'Audi Q5 55 TFSI e PHEV',
    brand: 'Audi',
    modelYear: 2026,
    powertrain: 'Plug-in Hybrid',
    category: 'Luxury',
    msrp: 58500,
    mpgCombined: 61, // MPGe
    cityMpg: 26,
    highwayMpg: 26,
    electricRangeMiles: 23,
    batteryKwh: 17.9,
    seatingCapacity: 5,
    cargoVolumeCuFt: 25.6,
    acceleration0to60Sec: 5.0,
    drivetrain: 'AWD',
    overallScore: 9.0,
    imageUrl: './images/Audi-Q5-55-TFSI-e-PHEV.webp',
    tagline:
      '362-hp quattro plug-in hybrid delivering sharp German handling and Virtual Cockpit plus.',
    pros: [
      '362 hp combined quattro performance',
      'Audi Virtual Cockpit Plus',
      'Quiet cabin',
    ],
    cons: ['23 miles electric range'],
    keyFeatures: [
      '362 hp quattro AWD',
      'Bang & Olufsen 3D sound system',
      'Virtual Cockpit Plus',
    ],
    usSalesRank: 42,
  },

  // 44. Mercedes-Benz GLE 450e
  {
    id: 'mercedes-gle-450e',
    name: 'Mercedes-Benz GLE 450e 4MATIC PHEV',
    brand: 'Mercedes-Benz',
    modelYear: 2026,
    powertrain: 'Plug-in Hybrid',
    category: 'Luxury',
    msrp: 71350,
    mpgCombined: 58, // MPGe
    cityMpg: 24,
    highwayMpg: 24,
    electricRangeMiles: 48,
    batteryKwh: 23.3,
    seatingCapacity: 5,
    cargoVolumeCuFt: 33.3,
    acceleration0to60Sec: 5.8,
    drivetrain: 'AWD',
    overallScore: 9.3,
    imageUrl: './images/Mercedes-Benz-GLE-450e-4MATIC-PHEV.webp',
    tagline:
      '48 miles pure electric range — among the longest for any plug-in hybrid SUV sold in the USA.',
    pros: [
      'Impressive 48 miles EV range',
      'Supports 60kW DC fast charging',
      'MBUX augmented reality navigation',
    ],
    cons: ['Heavy weight'],
    keyFeatures: [
      '48 miles electric range',
      '60kW DC Fast Charging support',
      'AIRMATIC air suspension option',
    ],
    usSalesRank: 43,
  },

  // 45. Honda HR-V
  {
    id: 'honda-hrv',
    name: 'Honda HR-V',
    brand: 'Honda',
    modelYear: 2026,
    powertrain: 'Gas',
    category: 'Subcompact',
    msrp: 25100,
    mpgCombined: 28,
    cityMpg: 26,
    highwayMpg: 32,
    seatingCapacity: 5,
    cargoVolumeCuFt: 24.4,
    acceleration0to60Sec: 9.4,
    drivetrain: 'FWD / AWD',
    overallScore: 8.7,
    imageUrl: './images/Honda-HR-V.webp',
    tagline:
      'Honda quality under $26k with smooth Civic chassis setup and versatile rear seats.',
    pros: [
      'Sub-$26k starting MSRP',
      'Civic platform handling',
      'Clean, modern cabin layout',
    ],
    cons: ['Engine acceleration is modest'],
    keyFeatures: [
      'Honda Sensing standard',
      'Real Time AWD available',
      'Sub-$26k base price',
    ],
    usSalesRank: 44,
  },

  // 46. Toyota Venza
  {
    id: 'toyota-venza',
    name: 'Toyota Venza Hybrid',
    brand: 'Toyota',
    modelYear: 2025,
    powertrain: 'Hybrid',
    category: 'Midsize',
    msrp: 35070,
    mpgCombined: 39,
    cityMpg: 40,
    highwayMpg: 37,
    seatingCapacity: 5,
    cargoVolumeCuFt: 28.8,
    acceleration0to60Sec: 7.6,
    drivetrain: 'AWD',
    overallScore: 9.0,
    imageUrl: './images/Toyota-Venza-Hybrid.webp',
    tagline:
      'Standard Star Gaze electrochromic glass roof with 39 MPG efficiency and sleek styling.',
    pros: [
      'Star Gaze frostable glass roof',
      '39 MPG combined',
      'Lexus-like quiet cabin',
    ],
    cons: ['Cargo space is tighter than RAV4 due to sloped glass'],
    keyFeatures: [
      'Star Gaze fixed panoramic roof',
      '39 MPG standard AWD',
      'Toyota Safety Sense 2.5+',
    ],
    usSalesRank: 45,
  },

  // 47. Porsche Cayenne E-Hybrid
  {
    id: 'porsche-cayenne-e-hybrid',
    name: 'Porsche Cayenne E-Hybrid',
    brand: 'Porsche',
    modelYear: 2026,
    powertrain: 'Plug-in Hybrid',
    category: 'Luxury',
    msrp: 91700,
    mpgCombined: 47, // MPGe
    cityMpg: 21,
    highwayMpg: 23,
    electricRangeMiles: 28,
    batteryKwh: 25.9,
    seatingCapacity: 5,
    cargoVolumeCuFt: 22.1,
    acceleration0to60Sec: 4.6,
    drivetrain: 'AWD',
    overallScore: 9.6,
    imageUrl: './images/Porsche-Cayenne-E-Hybrid.webp',
    tagline:
      '463-hp sports car DNA wrapped in a luxury performance hybrid crossover.',
    pros: [
      '463 hp V6 turbo PHEV',
      'Unsurpassed sports chassis dynamics',
      'Porsche Driver Experience display',
    ],
    cons: ['High purchase price'],
    keyFeatures: [
      '463 hp combined power',
      'PASM sport suspension',
      '11-inch passenger display option',
    ],
    usSalesRank: 46,
  },

  // 48. Chevrolet Tahoe V8 / Diesel
  {
    id: 'chevrolet-tahoe',
    name: 'Chevrolet Tahoe Duramax Diesel',
    brand: 'Chevrolet',
    modelYear: 2026,
    powertrain: 'Gas',
    category: '3-Row',
    msrp: 58195,
    mpgCombined: 24,
    cityMpg: 21,
    highwayMpg: 28,
    seatingCapacity: 8,
    cargoVolumeCuFt: 122.9,
    acceleration0to60Sec: 7.2,
    drivetrain: 'RWD / 4WD',
    overallScore: 9.1,
    imageUrl: './images/Chevrolet-Tahoe-Duramax-Diesel.webp',
    tagline:
      'Full-size body-on-frame American icon delivering 28 highway MPG with 3.0L Duramax Turbo-Diesel.',
    pros: [
      'Massive 122.9 cu ft cargo volume',
      '8,400 lbs towing capacity',
      '28 highway mpg diesel option',
    ],
    cons: ['Large parking footprint'],
    keyFeatures: [
      '17.7-inch infotainment display',
      'Super Cruise available',
      'Air Ride Adaptive Suspension',
    ],
    usSalesRank: 47,
  },

  // 49. Ford Bronco Sport
  {
    id: 'ford-bronco-sport',
    name: 'Ford Bronco Sport 1.5L',
    brand: 'Ford',
    modelYear: 2026,
    powertrain: 'Gas',
    category: 'Subcompact',
    msrp: 29795,
    mpgCombined: 26,
    cityMpg: 25,
    highwayMpg: 29,
    seatingCapacity: 5,
    cargoVolumeCuFt: 32.5,
    acceleration0to60Sec: 8.4,
    drivetrain: 'AWD',
    overallScore: 8.8,
    imageUrl: './images/Ford-Bronco-Sport-1.5L.webp',
    tagline:
      'Standard 4x4 off-road SUV with safari style roof for holding upright mountain bikes.',
    pros: [
      'Standard 4x4 on all trims',
      'G.O.A.T. modes terrain management',
      'Built-in rear bottle opener & safari roof',
    ],
    cons: ['26 MPG combined is lower than hybrids'],
    keyFeatures: [
      'G.O.A.T. terrain modes',
      'SYNC 4 13.2-inch screen',
      'Standard 4x4',
    ],
    usSalesRank: 48,
  },

  // 50. Subaru Solterra EV
  {
    id: 'subaru-solterra',
    name: 'Subaru Solterra EV',
    brand: 'Subaru',
    modelYear: 2026,
    powertrain: 'Full EV',
    category: 'Compact',
    msrp: 44995,
    mpgCombined: 104,
    cityMpg: 111,
    highwayMpg: 96,
    electricRangeMiles: 227,
    batteryKwh: 72.8,
    seatingCapacity: 5,
    cargoVolumeCuFt: 29.0,
    acceleration0to60Sec: 6.4,
    drivetrain: 'AWD',
    overallScore: 8.7,
    imageUrl: './images/Subaru-Solterra-EV.webp',
    tagline:
      'Standard Subaru AWD with 8.3 inches ground clearance in an all-electric crossover.',
    pros: [
      'Subaru Symmetrical Dual-Motor AWD',
      '8.3-inch ground clearance',
      'X-MODE with Grip Control',
    ],
    cons: ['227 miles range'],
    keyFeatures: [
      'Dual Motor AWD',
      'X-MODE Off-Road',
      'EyeSight Driver Assist',
    ],
    usSalesRank: 49,
  },
];

// Popular Baseline Vehicles for Quick Selection
const POPULAR_CURRENT_CARS = [
  { name: '2018 Toyota RAV4 Gas (26 MPG)', mpg: 26 },
  { name: '2017 Ford F-150 V6 (18 MPG)', mpg: 18 },
  { name: '2016 Jeep Grand Cherokee V6 (20 MPG)', mpg: 20 },
  { name: '2020 Chevrolet Tahoe V8 (16 MPG)', mpg: 16 },
  { name: '2019 Honda CR-V Gas (29 MPG)', mpg: 29 },
  { name: '2015 Nissan Altima (31 MPG)', mpg: 31 },
  { name: '2017 Subaru Forester Gas (25 MPG)', mpg: 25 },
  { name: 'Custom MPG Vehicle', mpg: 20 },
];

window.TOP_50_SUVS = TOP_50_SUVS;
window.POPULAR_CURRENT_CARS = POPULAR_CURRENT_CARS;
